### ISSUE TITLE
arrays of references don't transpile

### ISSUE THREAD

**Issue by ZakTax** [mickeyreiss/firemodel#14]
`array<reference<User>> staff;` produces an error `panic: firemodel:: schema.firemodel:62:20: unexpected "<" (expected ">")`

**Comment by mickeyreiss** [comment]
I was hoping to avoid this use-case for simplicity. Sounds like it'll be
required. Do you think firemodel needs arbitrary nesting, or is one level
sufficient?

`array<array<reference>>`

**Comment by ZakTax** [comment]
for now I think one level is sufficient
